/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int LEFT = 7;
  /** RegularExpression Id. */
  int AROUND = 8;
  /** RegularExpression Id. */
  int FRONT = 9;
  /** RegularExpression Id. */
  int BACK = 10;
  /** RegularExpression Id. */
  int NORTH = 11;
  /** RegularExpression Id. */
  int SOUTH = 12;
  /** RegularExpression Id. */
  int EAST = 13;
  /** RegularExpression Id. */
  int WEST = 14;
  /** RegularExpression Id. */
  int POP = 15;
  /** RegularExpression Id. */
  int GO = 16;
  /** RegularExpression Id. */
  int HOP = 17;
  /** RegularExpression Id. */
  int AssignTo = 18;
  /** RegularExpression Id. */
  int GoTO = 19;
  /** RegularExpression Id. */
  int TURN = 20;
  /** RegularExpression Id. */
  int FACE = 21;
  /** RegularExpression Id. */
  int PUT = 22;
  /** RegularExpression Id. */
  int PICK = 23;
  /** RegularExpression Id. */
  int MoveToThe = 24;
  /** RegularExpression Id. */
  int MoveInDir = 25;
  /** RegularExpression Id. */
  int JumpToThe = 26;
  /** RegularExpression Id. */
  int JumpInDir = 27;
  /** RegularExpression Id. */
  int NOP = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int DO = 30;
  /** RegularExpression Id. */
  int IF = 31;
  /** RegularExpression Id. */
  int THEN = 32;
  /** RegularExpression Id. */
  int ELSE = 33;
  /** RegularExpression Id. */
  int REPEAT = 34;
  /** RegularExpression Id. */
  int FACING = 35;
  /** RegularExpression Id. */
  int canPut = 36;
  /** RegularExpression Id. */
  int canPick = 37;
  /** RegularExpression Id. */
  int canMoveInDir = 38;
  /** RegularExpression Id. */
  int canJumpInDir = 39;
  /** RegularExpression Id. */
  int canMoveToThe = 40;
  /** RegularExpression Id. */
  int canJumpToThe = 41;
  /** RegularExpression Id. */
  int NOT = 42;
  /** RegularExpression Id. */
  int BALLOONS = 43;
  /** RegularExpression Id. */
  int CHIPS = 44;
  /** RegularExpression Id. */
  int ROBOT = 45;
  /** RegularExpression Id. */
  int VARS = 46;
  /** RegularExpression Id. */
  int PROCS = 47;
  /** RegularExpression Id. */
  int NUM = 48;
  /** RegularExpression Id. */
  int DIGIT = 49;
  /** RegularExpression Id. */
  int NAME = 50;
  /** RegularExpression Id. */
  int LETTER = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"LEFT\"",
    "\"AROUND\"",
    "\"FRONT\"",
    "\"BACK\"",
    "\"NORTH\"",
    "\"SOUTH\"",
    "\"EAST\"",
    "\"WEST\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"assignTo\"",
    "\"goto\"",
    "\"turn\"",
    "\"face\"",
    "\"Put\"",
    "\"Pick\"",
    "\"moveToThe\"",
    "\"moveInDir\"",
    "\"jumpToThe\"",
    "\"jumpInDir\"",
    "\"nop\"",
    "\"while\"",
    "\"do\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"repeat\"",
    "\"facing\"",
    "\"canPut\"",
    "\"canPick\"",
    "\"canMoveInDir\"",
    "\"canJumpInDir\"",
    "\"canMoveToThe\"",
    "\"canJumpToThe\"",
    "\"not\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "\"ROBOT_R\"",
    "\"VARS\"",
    "\"PROCS\"",
    "<NUM>",
    "<DIGIT>",
    "<NAME>",
    "<LETTER>",
    "\",\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
  };

}
