/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int POP = 7;
  /** RegularExpression Id. */
  int GO = 8;
  /** RegularExpression Id. */
  int HOP = 9;
  /** RegularExpression Id. */
  int AsignTo = 10;
  /** RegularExpression Id. */
  int GoTO = 11;
  /** RegularExpression Id. */
  int MOVE = 12;
  /** RegularExpression Id. */
  int TURN = 13;
  /** RegularExpression Id. */
  int FACE = 14;
  /** RegularExpression Id. */
  int PUT = 15;
  /** RegularExpression Id. */
  int PICK = 16;
  /** RegularExpression Id. */
  int MoveToThe = 17;
  /** RegularExpression Id. */
  int MoveInDir = 18;
  /** RegularExpression Id. */
  int JumpToThe = 19;
  /** RegularExpression Id. */
  int JumpInDir = 20;
  /** RegularExpression Id. */
  int NOP = 21;
  /** RegularExpression Id. */
  int BALLOONS = 22;
  /** RegularExpression Id. */
  int CHIPS = 23;
  /** RegularExpression Id. */
  int ROBOT = 24;
  /** RegularExpression Id. */
  int VARS = 25;
  /** RegularExpression Id. */
  int PROCS = 26;
  /** RegularExpression Id. */
  int NUM = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;
  /** RegularExpression Id. */
  int NAME = 29;
  /** RegularExpression Id. */
  int LETTER = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"asignTo\"",
    "\"goto\"",
    "\"move\"",
    "\"turn\"",
    "\"face\"",
    "\"Put\"",
    "\"Pick\"",
    "\"moveToThe\"",
    "\"moveInDir\"",
    "\"jumpToThe\"",
    "\"jumpInDir\"",
    "\"nop\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "\"ROBOT_R\"",
    "\"VARS\"",
    "\"PROCS\"",
    "<NUM>",
    "<DIGIT>",
    "<NAME>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
  };

}
